In [3]:
import numpy as np

an_array = np.array([3,33,333])

print(type(an_array))

<class 'numpy.ndarray'>


In [4]:
an_array2 = np.array([[3,33,333],[4,44,444]])
an_array2.shape

(2, 3)

In [5]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [6]:
print(an_array.shape)

(3,)


In [7]:
an_array[0] =888
print(an_array)

[888  33 333]


In [8]:
another = np.array([[11,12,13],[21,22,23]])
print(another)
print("the shape is 2 rows, 3 columns:", another.shape)
print("accessing elements[0,0], [0,1], and [1,0] of the narray: ", another[0,0], ", ",another[0,1], ", ",another[1,0])

[[11 12 13]
 [21 22 23]]
the shape is 2 rows, 3 columns: (2, 3)
accessing elements[0,0], [0,1], and [1,0] of the narray:  11 ,  12 ,  21


In [9]:
import numpy as np 
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [10]:
ex2 = np.full((3,3), 9.0)
print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [11]:
ex3 = np.eye(5,5)
print(ex3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
ex4 = np.ones((2,2))
print(ex4)

[[1. 1.]
 [1. 1.]]


In [13]:
print(ex4.shape)

print()
print(ex4[0,0])

(2, 2)

1.0


In [14]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.41946244 0.66875703]
 [0.86346471 0.45274808]]


In [15]:
import numpy as np
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [16]:
a_slice = an_array[0:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [17]:
print("Before:", an_array[0,1])
a_slice[0, 0] = 1000
print("After:",an_array[0,1])
print(an_array)

Before: 12
After: 1000
[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


In [18]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [19]:
row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [20]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [21]:
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [22]:
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print('original array:')
print(an_array)


original array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [23]:
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [24]:
for i,j in zip(row_indices,col_indices):
    print(i,", ",j)
''''for i in row_indices:
      for j in col_indices:'''

0 ,  0
1 ,  1
2 ,  2
3 ,  0


"'for i in row_indices:\n      for j in col_indices:"

In [25]:
print('value in the array at those indices: ',an_array[row_indices,col_indices])

value in the array at those indices:  [11 22 33 41]


In [26]:
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [27]:
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [28]:
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [29]:
print(an_array[filter])

[21 22 31 32]


In [30]:
an_array[an_array > 15]

array([21, 22, 31, 32])

In [31]:
an_array[an_array % 2 ==0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [32]:
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [33]:
ex2 = np.array([11.0,12.0])
print(ex2.dtype)

float64


In [34]:
ex3 = np.array([11.1,12.7], dtype=np.int64)
print(ex3.dtype)


int64


In [35]:
ex4 = np.array([11.1,12.7],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [36]:
ex5 = np.array([11,21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)


float64

[11. 21.]


In [37]:

import numpy as np
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


C:\Users\s.m.chishty\AppData\Local\Temp\ipykernel_6384\184873835.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([[111,112],[121,122]], dtype=np.int)


In [38]:
print(x + y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [39]:
print(x * y)
print()
print(np.add(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[322.1 324.1]
 [342.1 344.1]]


In [40]:
print(x - y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [41]:
print(x / y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [42]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [43]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [44]:
arr = 10 * np.random.randn(2,5)
print(arr)

[[-10.73846298  25.5844777    6.86533944   2.1477257  -13.21822601]
 [ -8.14601487  -7.0098136   -0.11337704  -9.23580965  -0.88997183]]


In [45]:
print(arr.mean())

-1.4754133136265373


In [46]:
print(arr.mean(axis = 1))

[ 2.12817077 -5.0789974 ]


In [47]:
print(arr.mean(axis = 0))

[-9.44223893  9.28733205  3.3759812  -3.54404197 -7.05409892]


In [48]:
print(arr.sum())

-14.754133136265372


In [49]:
print(np.median(arr, axis = 1))

[ 2.1477257 -7.0098136]


In [50]:
unsorted = np.random.randn(10)
print(unsorted)

[-0.40627442  0.10045346 -0.69526578 -0.7607846  -0.11143089 -0.56520764
 -0.63096333  0.11266047  0.44487464 -1.56548531]


In [51]:
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.56548531 -0.7607846  -0.69526578 -0.63096333 -0.56520764 -0.40627442
 -0.11143089  0.10045346  0.11266047  0.44487464]

[-0.40627442  0.10045346 -0.69526578 -0.7607846  -0.11143089 -0.56520764
 -0.63096333  0.11266047  0.44487464 -1.56548531]


In [52]:
unsorted.sort()
print(unsorted)

[-1.56548531 -0.7607846  -0.69526578 -0.63096333 -0.56520764 -0.40627442
 -0.11143089  0.10045346  0.11266047  0.44487464]


In [53]:
import numpy as np
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [54]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [55]:
print( np.intersect1d(s1, s2) )

['bulb' 'chair']


In [56]:
print( np.union1d(s1,s2) )

['bulb' 'chair' 'desk' 'lamp']


In [57]:
print( np.setdiff1d(s1,s2) )

['desk']


In [58]:
print( np.in1d(s1, s2))

[False  True  True]


In [59]:
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [60]:
add_rows = np.array([1, 0, 2])
print(add_rows)


[1 0 2]


In [61]:
y=start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [62]:
add_cols = np.array([[0, 1, 2, 3]])
print(add_cols)
add_cols = add_cols.T
print(add_cols)

[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


In [63]:
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [64]:
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [65]:
arrA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [66]:
arrB = np.array([0, 1, 0, 2])
print(arrB)

[0 1 0 2]


In [67]:
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


In [68]:
import numpy as np
x = np.array([23.23, 24.24])

In [69]:
np.save('an_array', x)

In [70]:
np.load('an_array.npy')

array([23.23, 24.24])

In [71]:
np.savetxt('array.txt', X=x, delimiter=',' )

In [72]:
!cat array.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [73]:
np.savetxt('array.txt', X=x, delimiter=',')
np.loadtxt('array.txt',delimiter=',')

array([23.23, 24.24])

In [74]:
x2d = np.array([[1,1], [1,1]])
y2d = np.array([[2,2], [2,2]])
print(x2d)
print()
print(y2d)
print()
print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))


[[1 1]
 [1 1]]

[[2 2]
 [2 2]]

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [75]:
a1d = np.array([9, 9])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


In [76]:
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[18 18]

[18 18]


In [79]:
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))

66


In [80]:
print(np.sum(ex1, axis=0))

[32 34]


In [81]:
print(np.sum(ex1, axis=1))

[23 43]


In [82]:
x = np.random.randn(8)
x

array([ 0.27183381,  0.87486005, -0.69350988,  0.84607096, -0.51596101,
        0.52268979, -0.01497822,  0.88991433])

In [84]:
y = np.random.randn(8)
y

array([ 1.59760019,  0.69308994,  1.42912778,  0.53612824, -0.75636236,
        1.21368506,  0.47790324, -0.58884569])

In [85]:
import numpy as np
x = np.random.randn(2,3)
y = np.random.randn(2,3)
np.maximum(x,y)

array([[ 0.38022428,  0.90031284,  0.78469812],
       [ 1.11994438,  1.47311694, -0.86009592]])